name: 'Sending message'
branding :
    icon : 'send'
    color : 'gray-dark'
author: 'BitFlib'
description: 'Sending a message'
inputs:
    repo:
        description: repo name
        required: true
    message:
        description: Message to be sent
        required: true
    developer:
        description: developer name starting the workflow
        required: true
    commit_sha:
        description: commit sha starting the workflow
        required: true
    server_url:
        description: server url
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - '${{ inputs.repo }}'
        - '${{ inputs.message }}'
        - '${{ inputs.developer }}'
        - '${{ inputs.commit_sha }}'
        - '${{ inputs.server_url }}'
